name: notify

on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ "main" ]

  # For testing only; to be removed
  workflow_dispatch:

jobs:
  pr_opened:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install dependencies
        run: sudo apt install libolm-dev libdbus-1-dev
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install matrix-commander
        run: pip install matrix-commander
      - name: login to matrix
        env:
          login: ${{ secrets.MATRIX_BOT_NAME }}
          password: ${{ secrets.MATRIX_BOT_PASSWORD }}
          server: ${{ secrets.MATRIX_SERVER }}
          room: ${{ secrets.MATRIX_MAINTAINERS_ROOM }}
        run: matrix-commander --login password --user-login "$login" --password "$password" --homeserver "$server" --device "GitHub Actions" --room-default "$room" -m "[PR ${{ github.event.action }}] ${{ github.event.pull_request.title }} (${{ github.event.pull_request.url }})"
